---
title: "Block Museum Calendar Automation"
---

## Overview

The Block Museum at Northwestern maintains weekly calendar archives documenting events and attendance. Creating these archives used to involve time-intensive manual editing: exporting Outlook calendars to PDF, manually transcribing event details into a Word template, and correcting data-entry mistakes. This project automated the entire pipeline with a Python application + Power Automate workflow.

## Implementation

The calendar archival undergoes the following steps:
1. Power Automate exports Outlook calendar to customized CSVs weekly and sends an email to employees when it is exported
    - Both manual and automatic Power Automate flows created for employees' convenience
2. The Python script (`block_converter.exe`) reads CSV, cleans data, and generates a formatted Word document
    - Filters exclude unnecessary events ("CANCELED", "OOO", "AUTOMATED" entries)
    - Events descriptions are validated to ensure they follow the museum's Required Fields Template
    - Creates a formatted Word document (`python-docx`) with proper fonts, spacing, indentation
3. One-click output uploads formatted `.docx` file to SharePoint

## Tools Used

Python • python-docx • Power Automate • Excel • Outlook • Word • SharePoint

## Repository Link

- [GitHub Repository](https://github.com/mmelliem/The-Block-Museum-Calendar-Project)

