project:
  type: website
  output-dir: docs

website:
  title: "Project Portfolio"
  
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd

  search: false 
  page-navigation: false 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-copy: false